name: Say hello

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  hello_word:
    runs-on: ubuntu-18.04
    steps:
      - name: Echo the message
        run: |
          echo "Hola Anderson!"