name: Say hello

on:
  push:
    branches:
      - master

jobs:
  hello_word:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the message
        run: |
          echo "Hola Anderson!"
      - name: Dime a fecha
        run: date
      - run: ls -l