name: Entrenamiento y Evaluación del Modelo

on: [push]

jobs:
  entrenamiento-evaluacion:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Matar el script evaluate_model.py
      run: pkill -f evaluate_model.py || true

    - name: Ejecutar el programa model_training.py
      run: python model_training.py

    - name: Ejecutar el programa evaluate_model.py
      run: python evaluate_model.py
